jobs:
    release:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Configure npm for publishing
              run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
              env:
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Mostrar .npmrc (sin token)
              run: head -n 1 .npmrc | sed 's/_authToken=.*$/_authToken=REDACTED/'

            - name: Validate npm authentication
              run: pnpm exec npm whoami
              env:
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Build the project
              run: pnpm run build

            - name: Run Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: pnpm exec semantic-release
